x_volume: 228.6
y_volume: 4.0
z_volume: 101.6
x_corner: 25.4
y_corner: 490.0
weld_gap: 6.0
weld_layer_height: 1.55
weld_layer_width: 8.5
weld_layer_overlap: 6.1
travel_speed: 1500.0
print_speed: 381.0
x_bed_size: 310.0
y_bed_size: 580.0
z_bed_size: 210.0
z_clearance: 60.0
