x_volume: 50.0
y_volume: 50.0
z_volume: 20.0
x_corner: 25.0
y_corner: 25.0
weld_gap: 8.0
weld_layer_height: 1.6
weld_layer_width: 8.5
weld_layer_overlap: 6.1
travel_speed: 1500.0
print_speed: 381.0
x_bed_size: 240.0
y_bed_size: 580.0
z_bed_size: 110.0
z_clearance: 30.0
